### ISSUE TITLE
Stopped working with DW

### ISSUE THREAD

**Issue by victor-sudakov** [ghewgill/ljdump#9]
Since some time this utility has stopped working with Dreamwidth. I'm sure the username and password in the ljdump.config are correct (I can login with them interactively into DW) but whenever I start ljdump I get the error:

```
$ ./ljdump.py
Fetching journal entries for: victor_sudakov
Traceback (most recent call last):
  File "./ljdump.py", line 378, in <module>
    ljdump(server, username, password, username, args.verbose)
  File "./ljdump.py", line 165, in ljdump
    }, Password))
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 101: 'Invalid password'>
```
FreeBSD 12.2-RELEASE-p7, python2.7 from ports.

**Comment by ebrannin-bw** [comment]
(Seems like this would be solved with #8)
